INSERT INTO client (client_id,first_name,last_name,age,email,user_role, user_name, user_password) VALUES (1,'Leah','Almeida',32,'leah_199@gmail.com', 'USER','leahh123', '#@$#$@#$ffff');
INSERT INTO client (client_id,first_name,last_name,age,email,user_role, user_name, user_password) VALUES (2,'Marlon','Brando',30,'mar_lon_b@gmail.com', 'USER','marloo35gg','#43ff221f');
INSERT INTO client (client_id,first_name,last_name,age,email,user_role, user_name, user_password) VALUES (3,'Joao','Pedro',42,'jp@gmail.com', 'USER','joaoooue223','34gd##54s');
INSERT INTO client (client_id,first_name,last_name,age,email,user_role, user_name, user_password) VALUES (4,'Carla','Ohana',23,'carlao@gmail.com', 'USER','carla1','#34eefxvd3#');
INSERT INTO client (client_id,first_name,last_name,age,email,user_role, user_name, user_password) VALUES (5,'Joaquim','Pereira',21,'jp22@gmail.com', 'USER','jpoaqu222','sfFf344fF');
INSERT INTO client (client_id,first_name,last_name,age,email,user_role, user_name, user_password) VALUES (6,'Jaddy','Santos',19,'jaddy123@gmail.com', 'USER','','');
INSERT INTO client (client_id,first_name,last_name,age,email,user_role, user_name, user_password) VALUES (7,'Jefferson','Thomas',54,'thomas_jefferson145@gmail.com', 'USER','','');
INSERT INTO client (client_id,first_name,last_name,age,email,user_role, user_name, user_password) VALUES (8,'Albert','Einstein',95,'genius@gmail.com', 'USER','','');
INSERT INTO client (client_id,first_name,last_name,age,email,user_role, user_name, user_password) VALUES (9,'Jeremias','Costa',33,'je_costa@gmail.com', 'USER','','');
INSERT INTO client (client_id,first_name,last_name,age,email,user_role, user_name, user_password) VALUES (10,'Caim','Abel',38,'caim_matou_abel@gmail.com', 'USER','','');
INSERT INTO client (client_id,first_name,last_name,age,email,user_role, user_name, user_password) VALUES (11,'Fernanda','Silva',45,'fesilva78@gmail.com', 'USER','','');
INSERT INTO client (client_id,first_name,last_name,age,email,user_role, user_name, user_password) VALUES (12,'Carlos','Henrique',41,'ch_alves_21@gmail.com', 'USER','','');